### ISSUE TITLE
Support for Rails 7.1

### ISSUE THREAD

**Issue by msxavi** [devise-two-factor/devise-two-factor#255]
To kick off the discussion: https://github.com/devise-two-factor/devise-two-factor/blob/main/devise-two-factor.gemspec#L25

Does anyone want to pick this up?

Cheers.

**Comment by msxavi** [comment]
Will start testing https://github.com/devise-two-factor/devise-two-factor/pull/256

**Comment by christobh** [comment]
Is this going to happen?

**Comment by bsedat** [comment]
I don't believe there is an issue here. The current version should allow for Rails v7.1 and v7.2. Closing for now unless I'm mistaken about something.
