### ISSUE TITLE
Remove faker or make it gem dependency?

### ISSUE THREAD

**Issue by mjankowski** [devise-two-factor/devise-two-factor#270]
Right now the `faker` gem is declared as a dev dependency in the gemspec.

I believe the only places it's used are two pretty trivial places within the shared specs (ie, not in the spec suite, but under lib/ in the examples meant to be included by applications using devise-two-factor).

Unless I'm missing something, I think this means that for any app using devise-two-factor and using those shared examples, faker becomes an actual dependency.

Thoughts on either:

- Convert those two usages to just use string interpolation, and drop faker from the gemspec
- Make faker a hard dependency of the gem, since a part of public not-dev-only interface does depend on it

Happy to open a PR for either of those directions.

**Comment by bsedat** [comment]
Fixed in #272.

**Comment by mjankowski** [comment]
Thanks for quick merge!

I see it's been ~2 yrs since release and I'm guessing things are pretty much in maintenance mode at this point, but -- any chance of version bump? Looks like the bulk of changes to main since the 5.0.0 release are documentation and CI config changes. With this PR and another one re: load order being the only code/user-facing changes since 5.0.

Anything else on horizon or planned for a 5.1?

**Comment by bsedat** [comment]
Yes, as you suspect this is mostly in maintenance mode. I've released everything we've got pending as v5.1.0.

**Comment by mjankowski** [comment]
Excellent, thanks.
